/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-07-26 13:26:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class crearPerfil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("  <!-- Enlace para estilos personalizados -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../styles/style.css\" />\r\n");
      out.write("  <!-- Enlace con la librería Tailwind -->\r\n");
      out.write("  <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("  <!-- Enlace para personalización de colores en Tailwind -->\r\n");
      out.write("  <script src=\"../../scripts/tailwind.js\"></script>\r\n");
      out.write("  <!-- Enlace con la libería DaisyUI -->\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/daisyui@4.12.2/dist/full.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("  <!-- Enlace para iconos de Font Awesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\"\r\n");
      out.write("    integrity=\"sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==\"\r\n");
      out.write("    crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("  <title>MDA Sena - Crear perfil</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"bg-mdaWhite grid content-center justify-center min-h-screen w-full p-2.5 bg-background4 bg-cover\">\r\n");
      out.write("  <!-- Ingrese aquí la estrucuta de la página -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Filtro imagen -->\r\n");
      out.write("  <div class=\"absolute top-0 left-0 min-h-screen w-full bg-mdaBlack_600\"></div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Contenedor de login -->\r\n");
      out.write("  <section class=\"container grid bg-white p-7 rounded-lg shadow-md w-full md:w-96 z-10\">\r\n");
      out.write("    <!--  -->\r\n");
      out.write("    <h3 class=\"text-mdaBlack text-xl text-center mb-2.5\">\r\n");
      out.write("      Bienvenido, ingrese los siguiente datos y cree su perfil\r\n");
      out.write("    </h3>\r\n");
      out.write("    <!-- Logo Sena y nombre del proyecto -->\r\n");
      out.write("    <div class=\"flex flex-row w-full h-20 mb-2.5\">\r\n");
      out.write("      <!-- Logo -->\r\n");
      out.write("      <div class=\"grid flex-grow place-items-center justify-end w-full\">\r\n");
      out.write("        <img class=\"w-12\" src=\"images/LogoNegro.svg\" alt=\"\" />\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- HR -->\r\n");
      out.write("      <div class=\"divider divider-horizontal\"></div>\r\n");
      out.write("      <!-- Nombre -->\r\n");
      out.write("      <div class=\"grid flex-grow place-items-center justify-start w-full\">\r\n");
      out.write("        <h1 class=\"text-2xl text-mdaBlack leading-none\">\r\n");
      out.write("          <span class=\"text-xl text-mdaGreen\">MDA</span> <br />\r\n");
      out.write("          Sena\r\n");
      out.write("        </h1>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <form action=\"svPerfil\" class=\"validarFormulario grid\" method=\"POST\" id=\"formularioPerfil\">\r\n");
      out.write("      <!-- Nombre -->\r\n");
      out.write("      <label class=\"bg-white text-mdaBlack input input-bordered flex items-center gap-2 mb-4\" id=\"labelName\">\r\n");
      out.write("        <i class=\"fa-solid fa-user text-gray-400\"></i>\r\n");
      out.write("        <input id=\"inputNombre\" type=\"text\" class=\"grow text-mdaBlack\" placeholder=\"Nombre\" autocomplete=\"off\"\r\n");
      out.write("               name=\"txtNombre\"/>\r\n");
      out.write("      </label>\r\n");
      out.write("      <!-- Apellidos -->\r\n");
      out.write("      <label class=\"bg-white text-mdaBlack input input-bordered flex items-center gap-2 mb-4\" id=\"labelLast\">\r\n");
      out.write("        <i class=\"fa-solid fa-user text-gray-400\"></i>\r\n");
      out.write("        <input id=\"inputApellido\" type=\"text\" class=\"grow text-mdaBlack\" placeholder=\"Apellidos\" autocomplete=\"off\"\r\n");
      out.write("               name=\"txtApellidos\"/>\r\n");
      out.write("      </label>\r\n");
      out.write("      <!-- Número de documento -->\r\n");
      out.write("      <label class=\"bg-white text-mdaBlack input input-bordered flex items-center gap-2 mb-4\" id=\"labelDocumento\">\r\n");
      out.write("        <i class=\"fa-solid fa-id-card text-gray-400\"></i>\r\n");
      out.write("        <input id=\"inputDocumento\" type=\"text\" class=\"grow text-mdaBlack\" placeholder=\"Número de documento\"\r\n");
      out.write("               autocomplete=\"off\" maxlength=\"20\" name=\"txtDocumento\"/>\r\n");
      out.write("      </label>\r\n");
      out.write("      <!-- Centro de formación -->\r\n");
      out.write("      <label class=\"bg-white text-mdaBlack input input-bordered flex items-center gap-2\" id=\"labelCentro\">\r\n");
      out.write("        <i class=\"fa-solid fa-hospital text-gray-400\"></i>\r\n");
      out.write("        <input id=\"inputCentro\" type=\"text\" class=\"grow text-mdaBlack\" placeholder=\"Centro de formación\"\r\n");
      out.write("               autocomplete=\"off\" name=\"txtCentro\"/>\r\n");
      out.write("      </label>\r\n");
      out.write("      <button class=\"btn bg-mdaGreen border-none text-white mt-4 hover:bg-mdaGreen\" type=\"submit\" id=\"btnForm\">\r\n");
      out.write("        Crear perfil\r\n");
      out.write("      </button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </section>\r\n");
      out.write("  <!-- Enlace para manejo del DOM -->\r\n");
      out.write("  <script src=\"scripts/validacionesPerfil.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
