/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-07-07 00:07:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Vistas.ventas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ventas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../Css/style.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\" integrity=\"sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n");
      out.write("  <title>Ventas</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <header class=\"nav__header\">\n");
      out.write("    <nav class=\"nav__container\">\n");
      out.write("      <div class=\"nav__items\">\n");
      out.write("        <ul class=\"nav__list\">\n");
      out.write("          <li class=\"nav__logo\">\n");
      out.write("            <img class=\"logo\" src=\"../../img/logo.png\" alt=\"\">\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav__item\">\n");
      out.write("            <a href=\"../inicio.jsp\" class=\"nav__link nav__link--titulo\">PIMERA EQUIPACION</a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"menu__toggle\">\n");
      out.write("        <span class=\"menu__toggle-icon\"><i class=\"fa-solid fa-bars\"></i></span>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("  </header>\n");
      out.write("  <main class=\"container container--size\">\n");
      out.write("      <section class=\"menu\">\n");
      out.write("        <h1 class=\"menu__title\">M E N U</h1>\n");
      out.write("        <ul class=\"menu__lista\">\n");
      out.write("          <li class=\"menu__item\">\n");
      out.write("            <a href=\"../inicio.jsp\" class=\"menu__link\" ><span class=\"icono__span\"><i class=\"fa-solid fa-house\"></i></span>Home</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"menu__item\">\n");
      out.write("            <a href=\"../datos.jsp\" class=\"menu__link\" ><span class=\"icono__span\"><i class=\"fa-solid fa-user-gear\"></i></span>Mis Datos</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"menu__item menu__item--selec\">\n");
      out.write("            <a href=\"ventas.jsp\" class=\"menu__link menu__link--selec\"><span class=\"icono__span\"><i class=\"fa-solid fa-cart-shopping\"></i></span>Ventas</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"menu__item\">\n");
      out.write("            <a href=\"../facturas/facturas.jsp\" class=\"menu__link\" ><span class=\"icono__span\"><i class=\"fa-solid fa-file-invoice\"></i></span>Facturas</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"menu__item\">\n");
      out.write("            <a href=\"../inventario/inventario.jsp\" class=\"menu__link\" ><span class=\"icono__span\"><i class=\"fa-solid fa-boxes-stacked\"></i></span>Inventario</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"menu__item\">\n");
      out.write("            <a href=\"../admin/usuarios.jsp\" class=\"menu__link\" ><span class=\"icono__span\"><i class=\"fa-solid fa-user\"></i></span>Usuarios</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"menu__item\">\n");
      out.write("            <a href=\"../admin/clientes.jsp\" class=\"menu__link\" ><span class=\"icono__span\"><i class=\"fa-solid fa-users-between-lines\"></i></span>Clientes</a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"menu__salir\">\n");
      out.write("          <a href=\"../../index.jsp\" class=\"menu__link menu__link--salir\" ><span class=\"icono__span\"><i class=\"fa-solid fa-right-from-bracket\"></i></span>Sign out</a>\n");
      out.write("        </div>\n");
      out.write("      </section>\n");
      out.write("      <section class=\"container__factura\">\n");
      out.write("        <div class=\"fatura__buscar\">\n");
      out.write("          <h1 class=\"title\">REALIZAR VENTA</h1>\n");
      out.write("          <form action=\"\" class=\"form__datos\">\n");
      out.write("            <div class=\"buscar\">\n");
      out.write("              <h2 class=\"cliente__title\">Cliente</h2>\n");
      out.write("              <div class=\"id__cliente\">\n");
      out.write("                <input type=\"number\" id=\"cdCliente\" class=\"codigo__cliente login__input\" placeholder=\"Codigo Cliente\">\n");
      out.write("                <button type=\"button\" class=\"button buscar__cliente\">Buscar</button>\n");
      out.write("                <input type=\"text\" class=\"codigo__cliente cliente__nombre\" readonly>\n");
      out.write("              </div>\n");
      out.write("              <h2 class=\"cliente__title\">Buscar Producto</h2>\n");
      out.write("              <div class=\"id__cliente\">\n");
      out.write("                <input type=\"number\" id=\"cdProducto\" class=\"codigo__cliente login__input\" placeholder=\"Codigo Producto\" >\n");
      out.write("                <button type=\"button\" class=\"button buscar__cliente\">Buscar</button>\n");
      out.write("                <input placeholder=\"Nombre\" type=\"text\" class=\"codigo__cliente cliente__nombre\" readonly>\n");
      out.write("                <div class=\"datos__producto\">\n");
      out.write("                  <input placeholder=\"Precio\" type=\"text\" class=\"codigo__cliente cliente__nombre margin\" readonly>\n");
      out.write("                  <input placeholder=\"Cantidad\" type=\"number\" class=\"codigo__cliente cliente__nombre \">\n");
      out.write("                  <select name=\"select\" class=\"codigo__cliente cliente__nombre margin margin--top\">\n");
      out.write("                    <option value=\"value1\">Seleccionar Talla</option>\n");
      out.write("                  </select>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"buscar__btn\">\n");
      out.write("                <button type=\"button\" class=\"button button__agregar\">Agregar Producto</button>\n");
      out.write("                <button type=\"button\" id=\"abrirModal\" class=\"button button__agregar  button__agregar--color\">Agragar Cliente</button>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"factura__tabla\">\n");
      out.write("              <div class=\"tabla\">\n");
      out.write("                <table class=\"tabla__factura\">\n");
      out.write("                    <thead class=\"tabla__th\">\n");
      out.write("                        <th>Id Producto</th>\n");
      out.write("                        <th>Nombre</th>\n");
      out.write("                        <th>Talla</th>\n");
      out.write("                        <th>Precio</th>\n");
      out.write("                        <th>Cantidad</th>\n");
      out.write("                        <th>Acciones</th>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody class=\"tabla__tb\">\n");
      out.write("                        <tr class=\"tabla__fila\">\n");
      out.write("                            <td class=\"id__producto tabla__td\">1</td>\n");
      out.write("                            <td class=\"nombre__producto tabla__td\">Camisa Real Madrid</td>\n");
      out.write("                            <td class=\"talla__producto tabla__td\">M</td>\n");
      out.write("                            <td class=\"precio__producto tabla__td\">120000</td>\n");
      out.write("                            <td class=\"cantidad__producto tabla__td\">1</td>\n");
      out.write("                            <td class=\"tabla__td\">\n");
      out.write("                              <button type=\"button\" class=\" button__link BtnEliminar\">Eliminar</button>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr class=\"tabla__fila\">\n");
      out.write("                          <td class=\"id__producto tabla__td\">1</td>\n");
      out.write("                          <td class=\"nombre__producto tabla__td\">Camisa Real Madrid</td>\n");
      out.write("                          <td class=\"talla__producto tabla__td\">M</td>\n");
      out.write("                          <td class=\"precio__producto tabla__td\">120000</td>\n");
      out.write("                          <td class=\"cantidad__producto tabla__td\">2</td>\n");
      out.write("                          <td class=\"tabla__td\">\n");
      out.write("                            <button type=\"button\" class=\" button__link BtnEliminar\">Eliminar</button>\n");
      out.write("                          </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr class=\"tabla__fila\">\n");
      out.write("                          <td class=\"id__producto tabla__td\">1</td>\n");
      out.write("                          <td class=\"nombre__producto tabla__td\">Camisa Real Madrid</td>\n");
      out.write("                          <td class=\"talla__producto tabla__td\">M</td>\n");
      out.write("                          <td class=\"precio__producto tabla__td\">120000</td>\n");
      out.write("                          <td class=\"cantidad__producto tabla__td\">3</td>\n");
      out.write("                          <td class=\"tabla__td\">\n");
      out.write("                            <button type=\"button\" class=\" button__link BtnEliminar\">Eliminar</button>\n");
      out.write("                          </td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"generar__factura\">\n");
      out.write("                <div class=\"buttons__facturas\">\n");
      out.write("                  <button type=\"submit\" class=\"button button__form btn__ventas\">Generar Factura</button>\n");
      out.write("                  <button type=\"button\" class=\"button__link button__link--size btn__ventas\">Cancelar</button>\n");
      out.write("                </div>\n");
      out.write("                <h2 class=\"total\">TOTAL: 1000000</h2>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </form>\n");
      out.write("        </div>        \n");
      out.write("      </section>\n");
      out.write("      <div id=\"ventanaModal\" class=\"container__modal\">\n");
      out.write("        <div class=\"contenido__modal\">\n");
      out.write("          <h2 class=\"modal__title--ventas\">REGISTRAR CLIENTE</h2>\n");
      out.write("          <form action=\"\" class=\"form__modal\">\n");
      out.write("              <div class=\"div__form\">\n");
      out.write("                  <label for=\"\" class=\"\">Documento: </label>\n");
      out.write("                  <input type=\"text\" class=\"modal__input\">\n");
      out.write("              </div>\n");
      out.write("              <div class=\"div__form\">\n");
      out.write("                  <label for=\"\" class=\"\">Nombre: </label>\n");
      out.write("                  <input type=\"text\" class=\"modal__input\">\n");
      out.write("              </div>\n");
      out.write("              <div class=\"div__form\">\n");
      out.write("                  <label for=\"\" class=\"\">Telefono: </label>\n");
      out.write("                  <input type=\"text\" class=\"modal__input\">\n");
      out.write("              </div>\n");
      out.write("              <div class=\"div__buttons\">\n");
      out.write("                  <button type=\"submit\" class=\"button button__modal\">Registrar</button>\n");
      out.write("                  <button type=\"button\" id=\"Cerrar__Modal\" class=\"button--alert button__modal button__modal--alert\">Cancelar</button>\n");
      out.write("              </div>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("  \n");
      out.write("  </main>\n");
      out.write("  <script src=\"../../js/ventas.js\"></script>\n");
      out.write("  <script src=\"../../js/menu.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
